### PR TITLE
CI: Update docker image

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
- Part of https://github.com/Lightning-AI/lightning/pull/13831.
- Updates PyTorch version from 1.8 to 1.9 as we don't build 1.8 images in the PL repo anymore. (Let's see if the CI allows it...)

## Before submitting
- [x] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the **[contributor guideline](https://github.com/PyTorchLightning/lightning-flash/tree/master/.github/CONTRIBUTING.md)**, Pull Request section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [n/a] Did you make sure to **update the documentation** with your changes?
- [n/a] Did you write any **new necessary tests**? [not needed for typos/docs]
- [n/a] Did you verify **new and existing tests pass** locally with your changes?
- [n/a] If you made a notable change (that affects users), did you **update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-flash/blob/master/CHANGELOG.md)**?

## PR review
 - [x] Is this pull request **ready for review**? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by kaushikb11 — APPROVED** [review]

**Review by krshrimali — APPROVED** [review]
Thanks! 🚀

**Comment by krshrimali** [comment]
Please don't worry about the failures, the CI is failing, and I'm working on it: #1410. :)

**Review by Borda — APPROVED** [review]

**Comment by krshrimali** [comment]
A couple of examples failures, namely: `
Lightning-AI.lightning-flash (Examples) (domain text with GPUs 0)` and `
Lightning-AI.lightning-flash (Examples) (domain video with GPUs 0,1)` are flaky. The text example is failing with some connection error to `HuggingFace.co` and the video example is failing with CUDA Runtime Error, I'll be re-running these tests to ensure they pass, and then we can merge this. (Other failures are being fixed, should be good very soon)

**Comment by akihironitta** [comment]
@krshrimali Thank you, Kush, for having a look at this! I'll re-re-run these three failing jobs and see if they pass this time :)

```
Lightning-AI.lightning-flash (Examples) Required
Lightning-AI.lightning-flash (Examples) (domain video with GPUs 0,1)
Lightning-AI.lightning-flash (Special)
```

**Review by krshrimali — APPROVED** [review]

**Pull request merged**
